build:
  version: "2.0"

accounts:
  message: "Welcome to EazyBank Account Related QA APIs"
  contactDetails:
    name: "Abhijeet Singh"
    email: "abhi@gmail.com"
  onCallSupport:
    - (555)555-1234
    - (555)123-8765